# This workflow crawls website of Ministry of Federal Affairs & General Administration MOFA Nepal and extract local government data.
name: Crawl MOFA website 0:00 UTC each month exactly at first day.

on:
  schedule:
  - cron: '0 0 1 * *'
#  push:
#    branches: [ "master" ]

permissions:
  contents: write

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
          
      - name: Install Python
        uses: actions/setup-python@v4.7.0
      
      - name: Install packages from PIP
        run: pip install -r requirements.txt

      - name: Execute crawler script
        run: ./extract_local_gov.py

      - name: Prepare git config
        run: git config --global user.email "mail.gauravnyaupane@gmail.com" && git config --global user.name "nightmaregaurav"

      - name: Add dummy file to trigger update
        run: date > last_crawled_on.date

      - name: Commit the change
        run: git add --all && git commit -m "Crawled on $(date)"

      - name: Push new file
        run: git push
